# Generated by Django 6.1.1 on 2026-09-05 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_parent', models.BooleanField(default=False, help_text='Exactly one parent manages members and tasks for the household.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive members cannot log in or complete tasks.')),
                ('display_name', models.CharField(blank=True, help_text='Optional name shown in the app. If empty, the username is used.', max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
